name: Laravel

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write

jobs:
  laravel-builds:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev
    - name: Show github context
      run: |
        echo "github.event_name=${{ github.event_name }}"
        echo "github.event.pull_request.merged=${{ github.event.pull_request.merged}}"
        echo "github.ref_name=${{ github.ref_name }}"
        echo "github.head_ref=${{ github.head_ref }}"
        echo "github.base_ref=${{ github.base_ref }}"
    - name: Override .gitignore
      run: cat .gitignore.build > .gitignore
    - name: Setup git
      run: |
        git config user.name  "build"
        git config user.email "5987588+github-actions@users.noreply.github.com"
    - name: Create branch
      run: git checkout -b build-develop
    - name: Commit
      run: |
        git add .
        git commit -m 'Update build files'
    - name: Push build
      run: git push -f origin build-develop